name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to Raspberry Pi
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -p 9999" ./ ruslan@188.194.162.213:~/hello-node



      - name: Restart Node.js app
        run: |
          ssh -o StrictHostKeyChecking=no -p 9999 ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} << 'EOF'
            cd ~/hello-node
            npm install
            pkill -f 'node server.js' || true
            nohup node server.js > app.log 2>&1 &
          EOF
          
            
          
