name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PI_SSH_KEY }}

      - name: Copy files to Raspberry Pi
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -p 9999" ./ ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }}:~/hello-node

      - name: Restart Node.js app
        run: |
          ssh -p 9999 ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} << 'EOF'
          pkill -f 'node server.js' || true
          nohup node ~/hello-node/server.js > ~/hello-node/app.log 2>&1 &
          EOF
